### ISSUE TITLE
Git worktree support

### ISSUE THREAD

**Issue by delanym** [rudikershaw/git-build-hook#44]
The plugin fails to detect the repository when in a worktree:
```
git worktree add ../newworktree
mvn -f ../newworktree
```
> Could not find or initialise a local git repository. A repository is required.

**Comment by rudikershaw** [comment]
Hi there, 

I'm afraid I didn't even realise the `git worktree` feature existed until you raised this issue. I haven't had much time to work on the project recently, but I am hoping to find a big chunk of time soon to fix some issues and make some improvements. 

I will take a look and see what I can work out. Would you be able to include a link to a minimal project that demonstrates the issue?

**Comment by delanym** [comment]
Just take your own project, create an alternative worktree, and try run the plugin (see updated command above)

**Comment by rudikershaw** [comment]
Looks like this is a bug in jgit (which we are using to run git commands in the plugin). 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

It's been known about since 2015 and hasn't been fixed. Looks like jgit is not being pro-actively maintained. There is a fork with a fix, but it is not published. I think it is probably safest to assume that jgit will never create a fix, so I will look into alternatives.

**Comment by rudikershaw** [comment]
I have released a fix in 3.4.0. You should be able to upgrade and you will be able to use worktrees without the error you were seeing. 

The behaviour has been changed so that the configure goal will not attempt to apply configuration changes in a worktree. You should see a warning in your build output to that effect.

**Comment by rudikershaw** [comment]
Resolving this issue. Feel free to open a new issue if you have any further problems.
